### PR TITLE
Fixed Linux compatibility

### LINKED ISSUE #6: Unable to select game executable on Linux
As title.

### LINKED ISSUE #7: Hyperlinks do not work on Linux
HostServices are bugged in OpenJDK 8. Fixed in Java 9.
Will need to fall back on using AWT Desktop.

### PR DESCRIPTION
**Pull request by ringosham**
Resolves #7
Resolves #6

### CODE REVIEW

File: src/com/ringosham/controller/SettingScreen.java [hunk 1]
```diff
@@ -136,13 +136,13 @@ private boolean checkGameDir(File dir) {
     public void changeGameExec() {
         String os = System.getProperty("os.name").toLowerCase();
         File game = null;
-        if (os.contains("win") || os.contains("nix")) {
+        if (os.contains("win") || os.equals("linux")) {
```
Comment (ringosham) [inline src/com/ringosham/controller/SettingScreen.java:139]: Apparently I can't even spell "Linux"
